'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { User } from '@supabase/supabase-js'
import { useRouter } from 'next/navigation'

// Copy to clipboard helper
const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch (err) {
    return false
  }
}

// Format results for copying
const formatForCopy = (perspective: string, parsedResult: any, icon: string) => {
  let formatted = `${icon} ${perspective.toUpperCase()} PERSPECTIVE\n`
  formatted += '━'.repeat(50) + '\n\n'
  
  if (parsedResult.summary) {
    formatted += `SUMMARY:\n${parsedResult.summary}\n\n`
  }
  
  if (parsedResult.competitive_position) {
    formatted += `COMPETITIVE POSITION:\n${parsedResult.competitive_position}\n\n`
  }
  
  if (parsedResult.opportunities?.length > 0) {
    formatted += `OPPORTUNITIES:\n`
    parsedResult.opportunities.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.risks?.length > 0) {
    formatted += `RISKS:\n`
    parsedResult.risks.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.strategic_risks?.length > 0) {
    formatted += `STRATEGIC RISKS:\n`
    parsedResult.strategic_risks.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.red_flags?.length > 0) {
    formatted += `🚨 CRITICAL ISSUES:\n`
    parsedResult.red_flags.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.compliance?.length > 0) {
    formatted += `COMPLIANCE ISSUES:\n`
    parsedResult.compliance.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.questions?.length > 0) {
    formatted += `CRITICAL QUESTIONS:\n`
    parsedResult.questions.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.recommendations?.length > 0) {
    formatted += `RECOMMENDATIONS:\n`
    parsedResult.recommendations.forEach((item: string, i: number) => {
      formatted += `${i + 1}. ${item}\n`
    })
    formatted += '\n'
  }
  
  if (parsedResult.recommendation) {
    formatted += `RECOMMENDATION:\n${parsedResult.recommendation}\n\n`
  }
  
  formatted += '━'.repeat(50) + '\n'
  formatted += 'Generated by Folding Vectors (foldingvectors.com)\n'
  
  return formatted
}

const PERSPECTIVES = [
  { id: 'investor', name: 'Investor', icon: '📊', description: 'Risk/return, valuation, competitive moat' },
  { id: 'legal', name: 'Legal', icon: '⚖️', description: 'Compliance, liability, contract risk' },
  { id: 'strategy', name: 'Strategy', icon: '📈', description: 'Market position, competitive dynamics' },
]

const SAMPLE_DOCUMENTS = {
  investment: `Investment Opportunity: EcoCharge Electric Vehicle Charging Network

Company Overview:
EcoCharge is building a nationwide network of fast-charging stations for electric vehicles. Currently operating 150 stations across 12 states with plans to expand to 1,000 stations within 24 months.

Financials:
- Current revenue: $8M annually
- Burn rate: $2M/month
- Raising: $50M Series B at $200M valuation
- Projected revenue Year 3: $100M

Market:
- EV adoption growing 40% YoY
- Charging infrastructure severely lacking in most regions
- Government subsidies available for charging infrastructure (up to 30% of costs)
- Major competitors: ChargePoint, EVgo

Team:
- CEO: Former Tesla executive with 10 years in EV infrastructure
- CTO: 15 years in energy infrastructure development
- CFO: Ex-Goldman Sachs, led energy sector deals

The Ask: $5M minimum investment for Series B participation`,

  contract: `EMPLOYMENT AGREEMENT

This Employment Agreement ("Agreement") is entered into as of January 1, 2025, between TechCorp Inc. ("Company") and John Smith ("Employee").

1. POSITION AND DUTIES
Employee shall serve as Senior Software Engineer and report to the VP of Engineering.

2. COMPENSATION
- Base salary: $180,000 per year
- Annual bonus: Up to 20% based on performance
- Stock options: 10,000 shares vesting over 4 years

3. NON-COMPETE CLAUSE
Employee agrees not to work for any competitor for 24 months after termination within 100-mile radius of Company headquarters.

4. INTELLECTUAL PROPERTY
All work product created during employment, including nights and weekends, shall be property of the Company.

5. TERMINATION
Either party may terminate with 30 days notice. Company may terminate immediately for cause.

6. CONFIDENTIALITY
Employee must maintain strict confidentiality of all Company information indefinitely.

7. DISPUTE RESOLUTION
Any disputes shall be resolved through binding arbitration in Delaware.`,

  strategy: `Market Entry Strategy: HealthTrack Wearables - European Expansion

Executive Summary:
HealthTrack is evaluating entry into the European wearable fitness device market, currently dominated by Fitbit (35% share), Garmin (28%), and Apple Watch (22%).

Our Product:
- Medical-grade heart rate monitoring (FDA approved)
- 14-day battery life vs. competitors' 5-7 days
- AI-powered health insights
- Price point: €299 (premium positioning)

Market Opportunity:
- European wearables market: €4.2B, growing 18% annually
- Medical wearables segment: €800M, growing 35% annually
- Aging population driving demand for health monitoring

Entry Strategy:
- Phase 1: Germany, UK, France (70% of market)
- Distribution: Direct-to-consumer + partnerships with healthcare providers
- Marketing: Medical certification as key differentiator
- Timeline: 18 months to profitability

Risks:
- GDPR compliance for health data
- CE marking certification required (6-9 months)
- Strong incumbent relationships with retailers
- Currency fluctuation exposure

Investment Required: €15M over 24 months`
}

export default function Home() {
  const [user, setUser] = useState<User | null>(null)
  const [loadingAuth, setLoadingAuth] = useState(true)
  const router = useRouter()
  
  const [text, setText] = useState('')
  const [email, setEmail] = useState('')
  const [selectedPerspectives, setSelectedPerspectives] = useState<string[]>(['investor'])
  const [results, setResults] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copiedId, setCopiedId] = useState<string | null>(null)

  const togglePerspective = (id: string) => {
    if (selectedPerspectives.includes(id)) {
      // Don't allow deselecting if it's the only one
      if (selectedPerspectives.length === 1) return
      setSelectedPerspectives(selectedPerspectives.filter(p => p !== id))
    } else {
      setSelectedPerspectives([...selectedPerspectives, id])
    }
  }

  const analyze = async () => {
    if (!text.trim()) {
      setError('Please enter some text to analyze')
      return
    }

    setLoading(true)
    setError('')
    setResults({})

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          text, 
          email: user?.email || email,
          perspectives: selectedPerspectives 
        })
      })

      const data = await response.json()

      if (response.ok) {
        setResults(data.results)
      } else {
        setError(data.error || 'Analysis failed')
      }
    } catch (err) {
      setError('Network error - please try again')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = async (perspectiveId: string, perspectiveName: string, icon: string, resultText: string) => {
    try {
      const cleaned = resultText
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim()
      const parsedResult = JSON.parse(cleaned)
      const formatted = formatForCopy(perspectiveName, parsedResult, icon)
      
      const success = await copyToClipboard(formatted)
      if (success) {
        setCopiedId(perspectiveId)
        setTimeout(() => setCopiedId(null), 2000)
      }
    } catch (e) {
      // Fallback: copy raw text
      await copyToClipboard(resultText)
      setCopiedId(perspectiveId)
      setTimeout(() => setCopiedId(null), 2000)
    }
  }

  // Check authentication
useEffect(() => {
  // Get initial session
  supabase.auth.getSession().then(({ data: { session } }) => {
    setUser(session?.user ?? null)
    setLoadingAuth(false)
  })

  // Listen for auth changes
  const {
    data: { subscription },
  } = supabase.auth.onAuthStateChange((_event, session) => {
    setUser(session?.user ?? null)
  })

  return () => subscription.unsubscribe()
}, [])

const handleSignOut = async () => {
  await supabase.auth.signOut()
  router.push('/auth/login')
}


  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 p-8">
      <div className="max-w-7xl mx-auto">
        
        {/* Header */}
        
        <div className="mb-12">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="text-5xl font-bold text-white mb-2">
                Folding Vectors
              </h1>
              <p className="text-slate-400 text-lg">
                Fold complexity into clarity
              </p>
            </div>
            
            {loadingAuth ? (
              <div className="text-slate-500">Loading...</div>
            ) : user ? (
              <div className="flex items-center gap-4">
                <div className="text-right">
                  <div className="text-slate-300 text-sm">{user.email}</div>
                  <div className="text-slate-500 text-xs">Free tier: 3 analyses/month</div>
                </div>
                <button
                  onClick={handleSignOut}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-sm text-slate-300 transition"
                >
                  Sign Out
                </button>
              </div>
            ) : (
              <button
                onClick={() => router.push('/auth/login')}
                className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition"
              >
                Sign In
              </button>
            )}
          </div>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          
          {/* Left: Input */}
          <div className="lg:col-span-1">
            {!user && (
              <div className="mb-4">
                <label className="block text-slate-300 mb-2 text-sm font-medium">
                  Email (optional)
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="hello@example.com"
                  className="w-full px-4 py-2 bg-slate-800 border border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
                />
              </div>
            )}

            <div className="mb-4">
              <label className="block text-slate-300 mb-3 text-sm font-medium">
                Select Perspectives
              </label>
              <div className="space-y-2">
                {PERSPECTIVES.map((perspective) => (
                  <button
                    key={perspective.id}
                    onClick={() => togglePerspective(perspective.id)}
                    className={`w-full text-left px-4 py-3 rounded-lg border-2 transition-all ${
                      selectedPerspectives.includes(perspective.id)
                        ? 'bg-blue-600 border-blue-500 text-white'
                        : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-slate-600'
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      <span className="text-2xl">{perspective.icon}</span>
                      <div className="flex-1">
                        <div className="font-semibold">{perspective.name}</div>
                        <div className="text-xs opacity-75 mt-1">
                          {perspective.description}
                        </div>
                      </div>
                      {selectedPerspectives.includes(perspective.id) && (
                        <span className="text-white">✓</span>
                      )}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <div className="mb-4">
              <div className="flex items-center justify-between mb-2">
                <label className="block text-slate-300 text-sm font-medium">
                  Document to Analyze
                </label>
                <div className="flex gap-2">
                  <button
                    onClick={() => setText(SAMPLE_DOCUMENTS.investment)}
                    className="text-xs text-blue-400 hover:text-blue-300 transition"
                  >
                    Investment
                  </button>
                  <span className="text-slate-600">•</span>
                  <button
                    onClick={() => setText(SAMPLE_DOCUMENTS.contract)}
                    className="text-xs text-blue-400 hover:text-blue-300 transition"
                  >
                    Contract
                  </button>
                  <span className="text-slate-600">•</span>
                  <button
                    onClick={() => setText(SAMPLE_DOCUMENTS.strategy)}
                    className="text-xs text-blue-400 hover:text-blue-300 transition"
                  >
                    Strategy
                  </button>
                </div>
              </div>
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Paste your investment memo, contract, proposal, or any document..."
                className="w-full h-64 px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-blue-500 font-mono text-sm"
              />
            </div>

            <button
              onClick={analyze}
              disabled={loading || !text.trim()}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:cursor-not-allowed text-white font-semibold px-6 py-3 rounded-lg transition-all"
            >
              {loading 
                ? `Analyzing with ${selectedPerspectives.length} perspective${selectedPerspectives.length > 1 ? 's' : ''}...`
                : `Analyze (${selectedPerspectives.length} selected)`
              }
            </button>

            {error && (
              <div className="mt-4 p-4 bg-red-900/50 border border-red-700 rounded-lg text-red-200 text-sm">
                {error}
              </div>
            )}
          </div>

          {/* Right: Results */}
          <div className="lg:col-span-2">
            <label className="block text-slate-300 mb-3 text-sm font-medium">
              Analysis Results
            </label>

            {loading && (
              <div className="flex items-center justify-center h-96 bg-slate-800 border border-slate-700 rounded-lg">
                <div className="text-center">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
                  <p className="text-slate-400">
                    Analyzing from {selectedPerspectives.length} perspective{selectedPerspectives.length > 1 ? 's' : ''}...
                  </p>
                  <p className="text-slate-500 text-sm mt-2">
                    This may take 10-30 seconds
                  </p>
                </div>
              </div>
            )}

            {Object.keys(results).length > 0 && !loading && (
              <div className="space-y-6">
                {selectedPerspectives.map((perspectiveId) => {
                  const perspective = PERSPECTIVES.find(p => p.id === perspectiveId)
                  const resultText = results[perspectiveId]
                  
                  if (!resultText) return null

                  // Try to parse JSON, fallback to raw text if it fails
                  let parsedResult: any = null
                  try {
                    // Remove markdown code blocks if present
                    const cleaned = resultText
                      .replace(/```json\n?/g, '')
                      .replace(/```\n?/g, '')
                      .trim()
                    parsedResult = JSON.parse(cleaned)
                  } catch (e) {
                    // If parsing fails, show raw text
                    parsedResult = null
                  }

                  return (
                    <div key={perspectiveId} className="bg-slate-800 border border-slate-700 rounded-lg overflow-hidden">
                      {/* Header */}
                      <div className="px-6 py-4 bg-slate-900 border-b border-slate-700 flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <span className="text-3xl">{perspective?.icon}</span>
                          <div>
                            <div className="font-semibold text-white text-lg">{perspective?.name} Perspective</div>
                            <div className="text-sm text-slate-400">{perspective?.description}</div>
                          </div>
                        </div>
                        <button
                          onClick={() => handleCopy(perspectiveId, perspective?.name || '', perspective?.icon || '', resultText)}
                          className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-sm text-slate-300 transition-all flex items-center gap-2"
                        >
                          {copiedId === perspectiveId ? (
                            <>
                              <span>✓</span>
                              <span>Copied!</span>
                            </>
                          ) : (
                            <>
                              <span>📋</span>
                              <span>Copy</span>
                            </>
                          )}
                        </button>
                      </div>

                      {/* Content */}
                      <div className="p-6">
                        {parsedResult ? (
                          <div className="space-y-6">
                            {/* Summary */}
                            {parsedResult.summary && (
                              <div>
                                <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-2">
                                  Summary
                                </h3>
                                <p className="text-slate-200 leading-relaxed">
                                  {parsedResult.summary}
                                </p>
                              </div>
                            )}

                            {/* Competitive Position (Strategy only) */}
                            {parsedResult.competitive_position && (
                              <div>
                                <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-2">
                                  Competitive Position
                                </h3>
                                <p className="text-slate-200 leading-relaxed">
                                  {parsedResult.competitive_position}
                                </p>
                              </div>
                            )}

                            {/* Opportunities */}
                            {parsedResult.opportunities && parsedResult.opportunities.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-green-400 uppercase tracking-wide mb-3">
                                  ✓ Opportunities
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.opportunities.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-green-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Risks */}
                            {parsedResult.risks && parsedResult.risks.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-red-400 uppercase tracking-wide mb-3">
                                  ⚠ Risks
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.risks.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-red-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Strategic Risks */}
                            {parsedResult.strategic_risks && parsedResult.strategic_risks.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-orange-400 uppercase tracking-wide mb-3">
                                  ⚠ Strategic Risks
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.strategic_risks.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-orange-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Red Flags (Legal only) */}
                            {parsedResult.red_flags && parsedResult.red_flags.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-red-500 uppercase tracking-wide mb-3">
                                  🚨 Critical Issues
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.red_flags.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3 p-3 bg-red-900/20 border border-red-800 rounded">
                                      <span className="text-red-400 mt-1">!</span>
                                      <span className="text-red-200">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Compliance (Legal only) */}
                            {parsedResult.compliance && parsedResult.compliance.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-blue-400 uppercase tracking-wide mb-3">
                                  Compliance Issues
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.compliance.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-blue-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Questions (Investor only) */}
                            {parsedResult.questions && parsedResult.questions.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-purple-400 uppercase tracking-wide mb-3">
                                  ? Critical Questions
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.questions.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-purple-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Recommendations */}
                            {parsedResult.recommendations && parsedResult.recommendations.length > 0 && (
                              <div>
                                <h3 className="text-sm font-semibold text-blue-400 uppercase tracking-wide mb-3">
                                  → Recommendations
                                </h3>
                                <ul className="space-y-2">
                                  {parsedResult.recommendations.map((item: string, i: number) => (
                                    <li key={i} className="flex items-start gap-3">
                                      <span className="text-blue-400 mt-1">•</span>
                                      <span className="text-slate-300">{item}</span>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Recommendation/Decision (Investor only) */}
                            {parsedResult.recommendation && (
                              <div className="mt-6 pt-6 border-t border-slate-700">
                                <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-2">
                                  Recommendation
                                </h3>
                                <p className="text-lg font-semibold text-white">
                                  {parsedResult.recommendation}
                                </p>
                              </div>
                            )}
                          </div>
                        ) : (
                          // Fallback: show raw text if JSON parsing failed
                          <pre className="text-slate-300 text-sm whitespace-pre-wrap font-mono">
                            {resultText}
                          </pre>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}

            {Object.keys(results).length === 0 && !loading && (
              <div className="flex items-center justify-center h-96 bg-slate-800 border border-slate-700 rounded-lg">
                <div className="text-center text-slate-500">
                  <div className="text-4xl mb-4">📄</div>
                  <p>Results will appear here...</p>
                  <p className="text-sm mt-2">Select perspectives and paste a document to analyze</p>
                </div>
              </div>
            )}
          </div>

        </div>

        {/* Footer */}
        <div className="text-center mt-12 text-slate-600 text-sm">
          <p>Powered by Claude Sonnet 4 • Built with Next.js • Multi-perspective analysis in seconds</p>
        </div>

      </div>
    </div>
  )
}