'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
import { User } from '@supabase/supabase-js'
import { useRouter } from 'next/navigation'
import { CheckIcon, CopyIcon, DownloadIcon, ShareIcon } from '@/components/icons'
import { ThemeToggle } from '@/components/ThemeToggle'
import { SynthesisView } from '@/components/SynthesisView'
import { exportToPDF, exportToWord, exportSynthesisToPDF, exportSynthesisToWord } from '@/lib/export-utils'
import { PerspectiveSelector } from '@/components/PerspectiveSelector'
import { PERSPECTIVES, getPerspectiveById, DEFAULT_PERSPECTIVES } from '@/lib/perspectives'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ParsedResult = Record<string, any>

// Copy to clipboard helper
const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}

// Format results for copying - handles any perspective
const formatForCopy = (perspectiveName: string, parsedResult: ParsedResult) => {
  let formatted = `${perspectiveName.toUpperCase()} ANALYSIS\n`
  formatted += '-'.repeat(50) + '\n\n'

  // Iterate through all keys and format them
  for (const [key, value] of Object.entries(parsedResult)) {
    if (!value) continue

    const label = key.replace(/_/g, ' ').toUpperCase()

    if (typeof value === 'string') {
      formatted += `${label}:\n${value}\n\n`
    } else if (Array.isArray(value) && value.length > 0) {
      formatted += `${label}:\n`
      value.forEach((item, i) => {
        formatted += `${i + 1}. ${item}\n`
      })
      formatted += '\n'
    }
  }

  formatted += '-'.repeat(50) + '\n'
  formatted += 'Generated by Folding Vectors (foldingvectors.com)\n'

  return formatted
}

// Format all results for copying
const formatAllForCopy = (perspectiveIds: string[], results: Record<string, string>) => {
  let formatted = '='.repeat(60) + '\n'
  formatted += 'FOLDING VECTORS - MULTI-PERSPECTIVE ANALYSIS\n'
  formatted += '='.repeat(60) + '\n\n'

  perspectiveIds.forEach((perspectiveId, index) => {
    const perspective = getPerspectiveById(perspectiveId)
    const resultText = results[perspectiveId]

    if (!resultText || !perspective) return

    try {
      const cleaned = resultText
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim()
      const parsedResult = JSON.parse(cleaned)

      if (index > 0) {
        formatted += '\n' + '-'.repeat(60) + '\n\n'
      }

      formatted += formatForCopy(perspective.name, parsedResult)
    } catch {
      // Skip if parsing fails
    }
  })

  return formatted
}

const SAMPLE_DOCUMENTS = {
  investment: `Investment Opportunity: EcoCharge Electric Vehicle Charging Network

Company Overview:
EcoCharge is building a nationwide network of fast-charging stations for electric vehicles. Currently operating 150 stations across 12 states with plans to expand to 1,000 stations within 24 months.

Financials:
- Current revenue: $8M annually
- Burn rate: $2M/month
- Raising: $50M Series B at $200M valuation
- Projected revenue Year 3: $100M

Market:
- EV adoption growing 40% YoY
- Charging infrastructure severely lacking in most regions
- Government subsidies available for charging infrastructure (up to 30% of costs)
- Major competitors: ChargePoint, EVgo

Team:
- CEO: Former Tesla executive with 10 years in EV infrastructure
- CTO: 15 years in energy infrastructure development
- CFO: Ex-Goldman Sachs, led energy sector deals

The Ask: $5M minimum investment for Series B participation`,

  contract: `EMPLOYMENT AGREEMENT

This Employment Agreement ("Agreement") is entered into as of January 1, 2025, between TechCorp Inc. ("Company") and John Smith ("Employee").

1. POSITION AND DUTIES
Employee shall serve as Senior Software Engineer and report to the VP of Engineering.

2. COMPENSATION
- Base salary: $180,000 per year
- Annual bonus: Up to 20% based on performance
- Stock options: 10,000 shares vesting over 4 years

3. NON-COMPETE CLAUSE
Employee agrees not to work for any competitor for 24 months after termination within 100-mile radius of Company headquarters.

4. INTELLECTUAL PROPERTY
All work product created during employment, including nights and weekends, shall be property of the Company.

5. TERMINATION
Either party may terminate with 30 days notice. Company may terminate immediately for cause.

6. CONFIDENTIALITY
Employee must maintain strict confidentiality of all Company information indefinitely.

7. DISPUTE RESOLUTION
Any disputes shall be resolved through binding arbitration in Delaware.`,

  strategy: `Market Entry Strategy: HealthTrack Wearables - European Expansion

Executive Summary:
HealthTrack is evaluating entry into the European wearable fitness device market, currently dominated by Fitbit (35% share), Garmin (28%), and Apple Watch (22%).

Our Product:
- Medical-grade heart rate monitoring (FDA approved)
- 14-day battery life vs. competitors' 5-7 days
- AI-powered health insights
- Price point: 299 EUR (premium positioning)

Market Opportunity:
- European wearables market: 4.2B EUR, growing 18% annually
- Medical wearables segment: 800M EUR, growing 35% annually
- Aging population driving demand for health monitoring

Entry Strategy:
- Phase 1: Germany, UK, France (70% of market)
- Distribution: Direct-to-consumer + partnerships with healthcare providers
- Marketing: Medical certification as key differentiator
- Timeline: 18 months to profitability

Risks:
- GDPR compliance for health data
- CE marking certification required (6-9 months)
- Strong incumbent relationships with retailers
- Currency fluctuation exposure

Investment Required: 15M EUR over 24 months`
}

// Admin emails with unlimited document length
const UNLIMITED_EMAILS = [
  'hello@foldingvectors.com',
  'adrien.lafeuille@gmail.com',
]
const DOCUMENT_CHAR_LIMIT = 10000

export default function Home() {
  const [user, setUser] = useState<User | null>(null)
  const [loadingAuth, setLoadingAuth] = useState(true)
  const [usageInfo, setUsageInfo] = useState<{ count: number; limit: number } | null>(null)
  const router = useRouter()

  const [text, setText] = useState('')
  const [email, setEmail] = useState('')
  const [selectedPerspectives, setSelectedPerspectives] = useState<string[]>(DEFAULT_PERSPECTIVES)
  const [results, setResults] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(false)
  const [loadingMessage, setLoadingMessage] = useState('')
  const [loadingPhase, setLoadingPhase] = useState(0)
  const [error, setError] = useState('')
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [viewMode, setViewMode] = useState<'list' | 'synthesis'>('list')
  const [uploadingFile, setUploadingFile] = useState(false)
  const [fileName, setFileName] = useState<string | null>(null)
  const [examplesOpen, setExamplesOpen] = useState(false)
  const [analysisId, setAnalysisId] = useState<string | null>(null)
  const [shareUrl, setShareUrl] = useState<string | null>(null)
  const [sharing, setSharing] = useState(false)
  const [shareCopied, setShareCopied] = useState(false)

  const fetchUsageInfo = async () => {
    if (!user) return

    const { data } = await supabase
      .from('profiles')
      .select('analyses_count, analyses_limit, plan')
      .eq('id', user.id)
      .single()

    if (data) {
      setUsageInfo({ count: data.analyses_count, limit: data.analyses_limit })
    }
  }

  // Check if user has unlimited document length
  const isUnlimitedUser = user?.email && UNLIMITED_EMAILS.includes(user.email)

  const analyze = async () => {
    if (!text.trim()) {
      setError('Please enter some text to analyze')
      return
    }

    // Check document length limit
    if (!isUnlimitedUser && text.length > DOCUMENT_CHAR_LIMIT) {
      setError(`Document exceeds ${DOCUMENT_CHAR_LIMIT.toLocaleString()} character limit. Please shorten your document or contact us for unlimited access.`)
      return
    }

    setLoading(true)
    setError('')
    setResults({})
    setLoadingPhase(0)
    setAnalysisId(null)
    setShareUrl(null)

    // Loading messages that cycle through
    const loadingMessages = [
      'Sending document to Claude...',
      'Analyzing from multiple viewpoints...',
      'Examining key details...',
      'Identifying opportunities and risks...',
      'Cross-referencing perspectives...',
      'Synthesizing insights...',
      'Preparing your analysis...',
      'Almost there...',
    ]

    // Start cycling through messages
    setLoadingMessage(loadingMessages[0])
    let messageIndex = 0
    const messageInterval = setInterval(() => {
      messageIndex = (messageIndex + 1) % loadingMessages.length
      setLoadingMessage(loadingMessages[messageIndex])
      setLoadingPhase(prev => prev + 1)
    }, 2500)

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text,
          email: user?.email || email,
          perspectives: selectedPerspectives
        })
      })

      const data = await response.json()

      if (response.ok) {
        setResults(data.results)
        setAnalysisId(data.analysisId)
        fetchUsageInfo()
      } else {
        if (data.error === 'limit_reached') {
          setError(data.message)
        } else {
          setError(data.error || 'Analysis failed')
        }
      }
    } catch {
      setError('Network error - please try again')
    } finally {
      clearInterval(messageInterval)
      setLoading(false)
      setLoadingMessage('')
    }
  }

  const handleCopy = async (perspectiveId: string, resultText: string) => {
    const perspective = getPerspectiveById(perspectiveId)
    if (!perspective) return

    try {
      const cleaned = resultText
        .replace(/```json\n?/g, '')
        .replace(/```\n?/g, '')
        .trim()
      const parsedResult = JSON.parse(cleaned)
      const formatted = formatForCopy(perspective.name, parsedResult)

      const success = await copyToClipboard(formatted)
      if (success) {
        setCopiedId(perspectiveId)
        setTimeout(() => setCopiedId(null), 2000)
      }
    } catch {
      await copyToClipboard(resultText)
      setCopiedId(perspectiveId)
      setTimeout(() => setCopiedId(null), 2000)
    }
  }

  const handleShare = async () => {
    if (!analysisId) return

    setSharing(true)
    try {
      const response = await fetch(`/api/analyses/${analysisId}/share`, {
        method: 'POST',
      })
      const data = await response.json()
      if (response.ok) {
        setShareUrl(data.shareUrl)
        await navigator.clipboard.writeText(data.shareUrl)
        setShareCopied(true)
        setTimeout(() => setShareCopied(false), 2000)
      }
    } catch (error) {
      console.error('Error creating share link:', error)
    } finally {
      setSharing(false)
    }
  }

  const handleCopyShareUrl = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl)
      setShareCopied(true)
      setTimeout(() => setShareCopied(false), 2000)
    }
  }

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null)
      setLoadingAuth(false)
    })

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null)
    })

    return () => subscription.unsubscribe()
  }, [])

  useEffect(() => {
    if (user) {
      fetchUsageInfo()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user])

  const handleSignOut = async () => {
    await supabase.auth.signOut()
    router.push('/auth/login')
  }

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    setUploadingFile(true)
    setError('')
    setFileName(file.name)

    try {
      const fileType = file.type
      let extractedText = ''

      if (fileType === 'text/plain' || file.name.endsWith('.txt')) {
        // Plain text file
        extractedText = await file.text()
      } else if (fileType === 'application/pdf' || file.name.endsWith('.pdf')) {
        // PDF file - we'll need to extract text on the server
        const formData = new FormData()
        formData.append('file', file)

        const response = await fetch('/api/extract-text', {
          method: 'POST',
          body: formData,
        })

        if (response.ok) {
          const data = await response.json()
          extractedText = data.text
        } else {
          throw new Error('Failed to extract text from PDF')
        }
      } else if (
        fileType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
        file.name.endsWith('.docx')
      ) {
        // DOCX file
        const formData = new FormData()
        formData.append('file', file)

        const response = await fetch('/api/extract-text', {
          method: 'POST',
          body: formData,
        })

        if (response.ok) {
          const data = await response.json()
          extractedText = data.text
        } else {
          throw new Error('Failed to extract text from DOCX')
        }
      } else if (fileType === 'application/msword' || file.name.endsWith('.doc')) {
        setError('Legacy .doc format is not supported. Please convert to .docx or paste the text directly.')
        setUploadingFile(false)
        return
      } else {
        // Try to read as text
        try {
          extractedText = await file.text()
        } catch {
          setError('Unsupported file format. Please use .txt, .pdf, or .docx files.')
          setUploadingFile(false)
          return
        }
      }

      if (extractedText.trim()) {
        // Check document length limit for file uploads
        if (!isUnlimitedUser && extractedText.length > DOCUMENT_CHAR_LIMIT) {
          setError(`Uploaded file exceeds ${DOCUMENT_CHAR_LIMIT.toLocaleString()} character limit (${extractedText.length.toLocaleString()} characters). Please use a shorter document or contact us for unlimited access.`)
          return
        }
        setText(extractedText)
      } else {
        setError('Could not extract text from the file. Please try pasting the content directly.')
      }
    } catch (err) {
      console.error('File upload error:', err)
      setError('Failed to read the file. Please try again or paste the text directly.')
    } finally {
      setUploadingFile(false)
      // Reset file input
      e.target.value = ''
    }
  }

  // Helper to format field labels
  const formatFieldLabel = (key: string): string => {
    return key
      .replace(/_/g, ' ')
      .replace(/([A-Z])/g, ' $1')
      .trim()
  }

  // Get icon for field type
  const getFieldIcon = (key: string): string => {
    const keyLower = key.toLowerCase()
    if (keyLower.includes('opportunit') || keyLower.includes('strength') || keyLower.includes('tailwind') || keyLower.includes('green')) return '+'
    if (keyLower.includes('risk') || keyLower.includes('gap') || keyLower.includes('concern') || keyLower.includes('headwind') || keyLower.includes('weakness')) return '-'
    if (keyLower.includes('flag') || keyLower.includes('critical') || keyLower.includes('attack') || keyLower.includes('vulnerab')) return '!'
    if (keyLower.includes('question')) return '?'
    if (keyLower.includes('recommend')) return '>'
    return '*'
  }

  // Render all fields from parsed result dynamically
  const renderParsedResult = (parsed: ParsedResult) => {
    const summaryKey = Object.keys(parsed).find(k => k.toLowerCase() === 'summary')
    const recommendationKey = Object.keys(parsed).find(k => k.toLowerCase() === 'recommendation')

    // Get all other keys (not summary or recommendation)
    const otherKeys = Object.keys(parsed).filter(k =>
      k.toLowerCase() !== 'summary' && k.toLowerCase() !== 'recommendation'
    )

    const summaryValue = summaryKey ? parsed[summaryKey] : null
    const recommendationValue = recommendationKey ? parsed[recommendationKey] : null

    return (
      <div className="space-y-6">
        {/* Summary first */}
        {summaryValue && (
          <div>
            <h3 className="text-xs uppercase tracking-wider opacity-60 mb-2">Summary</h3>
            <p className="leading-relaxed">{String(summaryValue)}</p>
          </div>
        )}

        {/* All other fields */}
        {otherKeys.map(key => {
          const value = parsed[key]
          if (!value) return null

          const label = formatFieldLabel(key)
          const icon = getFieldIcon(key)

          if (Array.isArray(value) && value.length > 0) {
            return (
              <div key={key}>
                <h3 className="text-xs uppercase tracking-wider opacity-60 mb-3">{label}</h3>
                <ul className="space-y-2">
                  {(value as string[]).map((item: string, i: number) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="opacity-40">{icon}</span>
                      <span>{String(item)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )
          } else if (typeof value === 'string') {
            return (
              <div key={key}>
                <h3 className="text-xs uppercase tracking-wider opacity-60 mb-2">{label}</h3>
                <p className="leading-relaxed">{value}</p>
              </div>
            )
          }
          return null
        })}

        {/* Recommendation last */}
        {recommendationValue && (
          <div className="mt-6 pt-6 border-t border-[var(--border)]">
            <h3 className="text-xs uppercase tracking-wider opacity-60 mb-2">Recommendation</h3>
            <p className="font-medium">{String(recommendationValue)}</p>
          </div>
        )}
      </div>
    )
  }

  // Landing page for logged-out users
  if (!loadingAuth && !user) {
    return (
      <div className="min-h-screen bg-[var(--bg)] text-[var(--text)]">
        {/* Header */}
        <div className="p-4 md:p-8">
          <div className="max-w-7xl mx-auto">
            <div className="flex items-center justify-between mb-6">
              <div>
                <h1 className="text-2xl md:text-4xl font-light tracking-tight mb-1">
                  Folding Vectors
                </h1>
              </div>
              <div className="flex items-center gap-2 md:gap-4">
                <ThemeToggle />
                <button
                  onClick={() => router.push('/auth/login')}
                  className="btn-primary px-4 md:px-6 py-2 text-sm font-medium"
                >
                  Sign In
                </button>
              </div>
            </div>
            <div className="border-b border-[var(--border)]" />
          </div>
        </div>

        {/* Hero Section */}
        <div className="px-4 md:px-8 py-12 md:py-16">
          <div className="max-w-3xl mx-auto text-center fade-in">
            <h2 className="text-3xl md:text-5xl font-light tracking-tight mb-6">
              Fold complexity into clarity
            </h2>
            <p className="text-lg md:text-xl opacity-60">
              Multi-perspective analysis for important documents.
            </p>
            <p className="text-lg md:text-xl opacity-60">
              See what you might be missing.
            </p>
          </div>
        </div>

        {/* Manifesto Section */}
        <div className="px-4 md:px-8 py-12 md:py-16 border-t border-[var(--border)]">
          <div className="max-w-3xl mx-auto slide-up">
            <h3 className="text-xs uppercase tracking-wider opacity-60 mb-6">Why Folding Vectors</h3>
            <div className="space-y-4 md:space-y-6 text-base md:text-lg leading-relaxed">
              <p>
                We gravitate toward perspectives that confirm what we already believe. It feels good to be right. But when stakes are high, confirmation bias becomes expensive.
              </p>
              <p>
                Every contract has clauses that favor the other party. Every investment has risks the pitch deck glosses over. Every strategy has blind spots the advocates cannot see.
              </p>
              <p>
                Folding Vectors forces confrontation with contrarian views. Upload a document, select perspectives that challenge your assumptions, and receive analysis from voices you might otherwise ignore: the skeptic, the ethicist, the adversary, the regulator.
              </p>
              <p className="font-medium">
                The goal is not to change your mind. It is to ensure that when you decide, you decide with open eyes.
              </p>
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="px-4 md:px-8 py-12 md:py-16 border-t border-[var(--border)]">
          <div className="max-w-5xl mx-auto">
            <div className="grid md:grid-cols-3 gap-8 md:gap-12">
              <div className="fade-in stagger-1">
                <h4 className="font-medium mb-3">20+ Perspectives</h4>
                <p className="text-sm opacity-60">
                  From Investor to Ethicist, Legal Counsel to Devil's Advocate. Choose up to 5 viewpoints for each analysis.
                </p>
              </div>
              <div className="fade-in stagger-2">
                <h4 className="font-medium mb-3">Synthesis View</h4>
                <p className="text-sm opacity-60">
                  See where perspectives agree and where they clash. Identify the tensions that deserve your attention.
                </p>
              </div>
              <div className="fade-in stagger-3">
                <h4 className="font-medium mb-3">Export Ready</h4>
                <p className="text-sm opacity-60">
                  Professional memo format in PDF or Word. Share with your team or keep for your records.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="px-4 md:px-8 py-12 md:py-16 border-t border-[var(--border)]">
          <div className="max-w-3xl mx-auto text-center">
            <h3 className="text-xl md:text-2xl font-light mb-4">Start analyzing with fresh eyes</h3>
            <p className="opacity-60 mb-6 md:mb-8">Free to try. No credit card required.</p>
            <button
              onClick={() => router.push('/auth/login')}
              className="btn-primary px-6 md:px-8 py-3 md:py-4 text-base md:text-lg font-medium w-full md:w-auto"
            >
              Try Now
            </button>
          </div>
        </div>

        {/* Footer */}
        <div className="px-4 md:px-8 py-6 md:py-8 border-t border-[var(--border)]">
          <div className="max-w-7xl mx-auto">
            <div className="flex flex-col items-center gap-4 md:flex-row md:justify-between md:gap-6">
              <div className="text-xs md:text-sm opacity-60 text-center md:text-left">
                Folding Vectors - Multi-perspective analysis in seconds
              </div>
              <div className="flex flex-col md:flex-row items-center gap-4 md:gap-6">
                <a href="mailto:hello@foldingvectors.com" className="text-xs md:text-sm opacity-60 hover:opacity-100 transition">
                  hello@foldingvectors.com
                </a>
                <div className="flex items-center gap-4">
                  <a
                    href="https://linkedin.com/company/folding-vectors/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="opacity-60 hover:opacity-100 transition"
                    aria-label="LinkedIn"
                  >
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                    </svg>
                  </a>
                  <a
                    href="https://github.com/foldingvectors/folding-vectors"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="opacity-60 hover:opacity-100 transition"
                    aria-label="GitHub"
                  >
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                    </svg>
                  </a>
                  <a
                    href="https://x.com/foldingvectors"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="opacity-60 hover:opacity-100 transition"
                    aria-label="X (Twitter)"
                  >
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--text)] p-4 md:p-8">
      <div className="max-w-7xl mx-auto">

        {/* Header */}
        <div className="mb-8 md:mb-12">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
            <div>
              <h1 className="text-2xl md:text-4xl font-light tracking-tight mb-1">
                Folding Vectors
              </h1>
              <p className="text-xs md:text-sm opacity-60">
                Multi-perspective document analysis
              </p>
            </div>

            <div className="flex items-center gap-2 md:gap-4">
              <ThemeToggle />
              {loadingAuth ? (
                <div className="opacity-40 loading-pulse">Loading...</div>
              ) : user ? (
                <div className="flex items-center gap-2 md:gap-6">
                  <div className="text-right hidden md:block">
                    <div className="text-sm">{user.email}</div>
                    {usageInfo && (
                      <div className="text-xs opacity-60">
                        {usageInfo.limit - usageInfo.count} analyses remaining
                      </div>
                    )}
                  </div>
                  <button
                    onClick={() => router.push('/dashboard')}
                    className="px-3 md:px-4 py-2 border border-[var(--border)] rounded-md text-xs md:text-sm hover:opacity-60 transition"
                  >
                    Dashboard
                  </button>
                  <button
                    onClick={handleSignOut}
                    className="px-3 md:px-4 py-2 border border-[var(--border)] rounded-md text-xs md:text-sm hover:opacity-60 transition"
                  >
                    Sign Out
                  </button>
                </div>
              ) : (
                <button
                  onClick={() => router.push('/auth/login')}
                  className="btn-primary px-4 md:px-6 py-2 text-sm font-medium"
                >
                  Sign In
                </button>
              )}
            </div>
          </div>
          <div className="border-b border-[var(--border)]" />
        </div>

        <div className="grid lg:grid-cols-3 gap-6 md:gap-12">

          {/* Left: Input */}
          <div className="lg:col-span-1 space-y-6">
            {!user && (
              <div>
                <label className="block text-xs uppercase tracking-wider mb-2 opacity-60">
                  Email (optional)
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="hello@example.com"
                  className="w-full px-4 py-3 bg-transparent border border-[var(--border)] rounded-md text-[var(--text)] placeholder:opacity-40 focus:outline-none focus:ring-1 focus:ring-[var(--text)]"
                />
              </div>
            )}

            {/* New Perspective Selector */}
            <div className="mb-2">
              <PerspectiveSelector
                selected={selectedPerspectives}
                onChange={setSelectedPerspectives}
                maxSelections={5}
              />
            </div>

            {/* Usage meter */}
            {user && usageInfo && (
              <div className="p-4 border border-[var(--border)] rounded-md">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs uppercase tracking-wider opacity-60">
                    Today
                  </span>
                  <span className="text-xs">
                    {usageInfo.count} / {usageInfo.limit}
                  </span>
                </div>

                <div className="w-full h-1 bg-transparent border border-[var(--border)] rounded-md">
                  <div
                    className="h-full bg-[var(--text)] transition-all"
                    style={{ width: `${Math.min((usageInfo.count / usageInfo.limit) * 100, 100)}%` }}
                  />
                </div>

                {usageInfo.count >= usageInfo.limit && (
                  <div className="mt-3 text-xs">
                    <p className="font-medium mb-1">Daily limit reached</p>
                    <p className="opacity-60">Your limit resets at midnight.</p>
                  </div>
                )}
              </div>
            )}

            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs uppercase tracking-wider opacity-60">
                  Document
                </label>
                <div className="relative">
                  <button
                    onClick={() => setExamplesOpen(!examplesOpen)}
                    className="text-xs underline hover:opacity-60 transition flex items-center gap-1"
                  >
                    Examples
                    <svg
                      width="10"
                      height="10"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      className={`transition-transform ${examplesOpen ? 'rotate-180' : ''}`}
                    >
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </button>
                  {examplesOpen && (
                    <div className="absolute right-0 top-full mt-1 bg-[var(--bg)] border border-[var(--border)] rounded-md shadow-lg z-10 min-w-[120px]">
                      <button
                        onClick={() => {
                          setText(SAMPLE_DOCUMENTS.investment)
                          setExamplesOpen(false)
                        }}
                        className="block w-full text-left px-3 py-2 text-xs hover:bg-[var(--hover-bg)] transition"
                      >
                        Investment
                      </button>
                      <button
                        onClick={() => {
                          setText(SAMPLE_DOCUMENTS.contract)
                          setExamplesOpen(false)
                        }}
                        className="block w-full text-left px-3 py-2 text-xs hover:bg-[var(--hover-bg)] transition"
                      >
                        Contract
                      </button>
                      <button
                        onClick={() => {
                          setText(SAMPLE_DOCUMENTS.strategy)
                          setExamplesOpen(false)
                        }}
                        className="block w-full text-left px-3 py-2 text-xs hover:bg-[var(--hover-bg)] transition"
                      >
                        Strategy
                      </button>
                    </div>
                  )}
                </div>
              </div>

              {/* File Upload */}
              <div className="mb-3">
                <label className="flex items-center justify-center gap-2 px-4 py-3 border border-dashed border-[var(--border)] rounded-md cursor-pointer hover:border-[var(--text)] transition">
                  <input
                    type="file"
                    accept=".txt,.pdf,.docx"
                    onChange={handleFileUpload}
                    className="hidden"
                    disabled={uploadingFile}
                  />
                  {uploadingFile ? (
                    <span className="text-sm opacity-60">Extracting text...</span>
                  ) : (
                    <>
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                        <polyline points="17 8 12 3 7 8" />
                        <line x1="12" y1="3" x2="12" y2="15" />
                      </svg>
                      <span className="text-sm">
                        {fileName ? fileName : 'Upload document (.txt, .pdf, .docx)'}
                      </span>
                    </>
                  )}
                </label>
              </div>

              <textarea
                value={text}
                onChange={(e) => {
                  setText(e.target.value)
                  setFileName(null)
                }}
                placeholder="Or paste your document here..."
                className="w-full h-64 px-4 py-3 bg-transparent border border-[var(--border)] rounded-md text-[var(--text)] placeholder:opacity-40 focus:outline-none focus:ring-1 focus:ring-[var(--text)] font-mono text-sm resize-none"
              />

              {/* Character counter */}
              {text.length > 0 && (
                <div className={`text-xs mt-2 ${!isUnlimitedUser && text.length > DOCUMENT_CHAR_LIMIT ? 'text-red-500' : 'opacity-60'}`}>
                  {text.length.toLocaleString()} / {isUnlimitedUser ? 'unlimited' : DOCUMENT_CHAR_LIMIT.toLocaleString()} characters
                  {!isUnlimitedUser && text.length > DOCUMENT_CHAR_LIMIT && (
                    <span className="ml-2">(exceeds limit)</span>
                  )}
                </div>
              )}
            </div>

            <button
              onClick={analyze}
              disabled={loading || !text.trim() || selectedPerspectives.length === 0}
              className="w-full btn-primary py-3 font-medium"
            >
              {loading
                ? `Analyzing...`
                : `Analyze (${selectedPerspectives.length} perspective${selectedPerspectives.length > 1 ? 's' : ''})`
              }
            </button>

            {error && (
              <div className="p-4 border border-[var(--border)] rounded-md text-sm">
                {error}
              </div>
            )}
          </div>

          {/* Right: Results */}
          <div className="lg:col-span-2">
            <div className="flex items-center justify-between mb-4">
              <label className="text-xs uppercase tracking-wider opacity-60">
                Results
              </label>

              {Object.keys(results).length > 0 && !loading && (
                <div className="flex items-center gap-3">
                  {/* View Toggle */}
                  <div className="flex items-center">
                    <button
                      onClick={() => setViewMode('synthesis')}
                      className={`px-3 py-1.5 border text-xs transition rounded-l-md ${
                        viewMode === 'synthesis'
                          ? 'bg-[var(--text)] text-[var(--bg)] border-[var(--border)]'
                          : 'border-[var(--border)] hover:opacity-60'
                      }`}
                    >
                      Synthesis
                    </button>
                    <button
                      onClick={() => setViewMode('list')}
                      className={`px-3 py-1.5 border border-l-0 text-xs transition rounded-r-md ${
                        viewMode === 'list'
                          ? 'bg-[var(--text)] text-[var(--bg)] border-[var(--border)]'
                          : 'border-[var(--border)] hover:opacity-60'
                      }`}
                    >
                      Details
                    </button>
                  </div>

                  <button
                    onClick={async () => {
                      const allText = formatAllForCopy(selectedPerspectives, results)
                      await copyToClipboard(allText)
                      setCopiedId('all')
                      setTimeout(() => setCopiedId(null), 2000)
                    }}
                    className="px-4 py-2 border border-[var(--border)] rounded-md text-sm flex items-center gap-2 hover:opacity-60 transition"
                  >
                    {copiedId === 'all' ? (
                      <>
                        <CheckIcon size={14} />
                        <span>Copied</span>
                      </>
                    ) : (
                      <>
                        <CopyIcon size={14} />
                        <span>Copy All</span>
                      </>
                    )}
                  </button>

                  <button
                    onClick={() => exportToPDF(selectedPerspectives, results, 'Analysis Report', user?.email || email || undefined)}
                    className="px-4 py-2 border border-[var(--border)] rounded-md text-sm flex items-center gap-2 hover:opacity-60 transition"
                  >
                    <DownloadIcon size={14} />
                    <span>PDF</span>
                  </button>

                  <button
                    onClick={() => exportToWord(selectedPerspectives, results, 'Analysis Report', user?.email || email || undefined)}
                    className="px-4 py-2 border border-[var(--border)] rounded-md text-sm flex items-center gap-2 hover:opacity-60 transition"
                  >
                    <DownloadIcon size={14} />
                    <span>Word</span>
                  </button>

                  {analysisId && (
                    shareUrl ? (
                      <button
                        onClick={handleCopyShareUrl}
                        className="px-4 py-2 border border-[var(--border)] rounded-md text-sm flex items-center gap-2 hover:opacity-60 transition"
                      >
                        {shareCopied ? (
                          <>
                            <CheckIcon size={14} />
                            <span>Copied!</span>
                          </>
                        ) : (
                          <>
                            <ShareIcon size={14} />
                            <span>Copy Link</span>
                          </>
                        )}
                      </button>
                    ) : (
                      <button
                        onClick={handleShare}
                        disabled={sharing}
                        className="px-4 py-2 border border-[var(--border)] rounded-md text-sm flex items-center gap-2 hover:opacity-60 transition disabled:opacity-40"
                      >
                        <ShareIcon size={14} />
                        <span>{sharing ? 'Creating...' : 'Share'}</span>
                      </button>
                    )
                  )}
                </div>
              )}
            </div>

            {/* Share URL display */}
            {shareUrl && (
              <div className="mb-6 p-4 border border-[var(--border)] rounded-md bg-[var(--hover-bg)]">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="text-xs uppercase tracking-wider opacity-60 mb-1">Shareable Link</div>
                    <div className="text-sm font-mono truncate opacity-80">{shareUrl}</div>
                  </div>
                  <button
                    onClick={handleCopyShareUrl}
                    className="px-3 py-1.5 border border-[var(--border)] rounded-md text-xs flex items-center gap-2 hover:opacity-60 transition shrink-0"
                  >
                    {shareCopied ? (
                      <>
                        <CheckIcon size={12} />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <CopyIcon size={12} />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}

            {loading && (
              <div className="space-y-6">
                {selectedPerspectives.map((perspectiveId, index) => {
                  const perspective = getPerspectiveById(perspectiveId)
                  return (
                    <div
                      key={perspectiveId}
                      className="border border-[var(--border)] rounded-md fade-in"
                      style={{ animationDelay: `${index * 0.1}s` }}
                    >
                      <div className="px-4 md:px-6 py-4 border-b border-[var(--border)] flex items-center gap-3">
                        <div className="w-8 h-8 border border-[var(--border)] rounded-md flex items-center justify-center text-xs font-medium loading-pulse">
                          {perspective?.name.charAt(0) || '?'}
                        </div>
                        <div className="flex-1">
                          <div className="font-medium text-sm loading-pulse">{perspective?.name || 'Loading...'}</div>
                          <div className="text-xs opacity-40">{perspective?.coreFocus || 'Analyzing...'}</div>
                        </div>
                        <div className="text-xs opacity-40 loading-pulse">Processing...</div>
                      </div>
                      <div className="p-4 md:p-6 space-y-4">
                        <div className="h-4 loading-skeleton w-full rounded" />
                        <div className="h-4 loading-skeleton w-5/6 rounded" />
                        <div className="h-4 loading-skeleton w-4/6 rounded" />
                      </div>
                    </div>
                  )
                })}

                <div className="text-center mt-6 space-y-3">
                  <div className="flex items-center justify-center gap-2">
                    <div className="w-2 h-2 bg-[var(--text)] rounded-full loading-pulse" />
                    <div className="w-2 h-2 bg-[var(--text)] rounded-full loading-pulse" style={{ animationDelay: '0.3s' }} />
                    <div className="w-2 h-2 bg-[var(--text)] rounded-full loading-pulse" style={{ animationDelay: '0.6s' }} />
                  </div>
                  <p className="text-sm font-medium fade-in" key={loadingPhase}>
                    {loadingMessage || `Analyzing with ${selectedPerspectives.length} perspective${selectedPerspectives.length > 1 ? 's' : ''}...`}
                  </p>
                  <p className="text-xs opacity-40">
                    {selectedPerspectives.map(id => getPerspectiveById(id)?.name).filter(Boolean).join(' · ')}
                  </p>
                </div>
              </div>
            )}

            {Object.keys(results).length > 0 && !loading && viewMode === 'synthesis' && (
              <div className="border border-[var(--border)] rounded-md p-6">
                <SynthesisView
                  perspectives={selectedPerspectives}
                  results={results}
                  onExportPDF={() => exportSynthesisToPDF(selectedPerspectives, results, 'Analysis Synthesis', user?.email || email || undefined)}
                  onExportWord={() => exportSynthesisToWord(selectedPerspectives, results, 'Analysis Synthesis', user?.email || email || undefined)}
                />
              </div>
            )}

            {Object.keys(results).length > 0 && !loading && viewMode === 'list' && (
              <div className="space-y-6">
                {selectedPerspectives.map((perspectiveId) => {
                  const perspective = getPerspectiveById(perspectiveId)
                  const resultText = results[perspectiveId]

                  if (!resultText || !perspective) return null

                  let parsedResult: ParsedResult | null = null
                  try {
                    const cleaned = resultText
                      .replace(/```json\n?/g, '')
                      .replace(/```\n?/g, '')
                      .trim()
                    parsedResult = JSON.parse(cleaned) as ParsedResult
                  } catch {
                    parsedResult = null
                  }

                  return (
                    <div key={perspectiveId} className="border border-[var(--border)] rounded-md">
                      {/* Header */}
                      <div className="px-6 py-4 border-b border-[var(--border)] flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div className="w-8 h-8 border border-[var(--border)] rounded-md flex items-center justify-center text-xs font-medium">
                            {perspective.name.charAt(0)}
                          </div>
                          <div>
                            <div className="font-medium">{perspective.name}</div>
                            <div className="text-xs opacity-60">{perspective.coreFocus}</div>
                          </div>
                        </div>
                        <button
                          onClick={() => handleCopy(perspectiveId, resultText)}
                          className="px-3 py-1.5 border border-[var(--border)] rounded-md text-xs flex items-center gap-2 hover:opacity-60 transition"
                        >
                          {copiedId === perspectiveId ? (
                            <>
                              <CheckIcon size={12} />
                              <span>Copied</span>
                            </>
                          ) : (
                            <>
                              <CopyIcon size={12} />
                              <span>Copy</span>
                            </>
                          )}
                        </button>
                      </div>

                      {/* Content */}
                      <div className="p-6">
                        {parsedResult ? (
                          renderParsedResult(parsedResult)
                        ) : (
                          <pre className="text-sm whitespace-pre-wrap font-mono opacity-80">
                            {resultText}
                          </pre>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}

            {Object.keys(results).length === 0 && !loading && (
              <div className="border border-[var(--border)] rounded-md p-12 text-center">
                <h3 className="text-lg font-medium mb-2">
                  Ready to Analyze
                </h3>
                <p className="text-sm opacity-60 max-w-md mx-auto mb-6">
                  Select perspectives, paste a document, and click Analyze to see insights from multiple professional viewpoints.
                </p>

                <div className="text-xs opacity-40">
                  {PERSPECTIVES.length} perspectives available across 5 categories
                </div>
              </div>
            )}
          </div>

        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-[var(--border)]">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="text-xs opacity-60">
              Folding Vectors - Multi-perspective analysis in seconds
            </div>
            <div className="flex items-center gap-6">
              <a href="mailto:hello@foldingvectors.com" className="text-xs opacity-60 hover:opacity-100 transition">
                hello@foldingvectors.com
              </a>
              <div className="flex items-center gap-3">
                <a
                  href="https://linkedin.com/company/folding-vectors/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="opacity-60 hover:opacity-100 transition"
                  aria-label="LinkedIn"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                  </svg>
                </a>
                <a
                  href="https://github.com/foldingvectors/folding-vectors"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="opacity-60 hover:opacity-100 transition"
                  aria-label="GitHub"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                  </svg>
                </a>
                <a
                  href="https://x.com/foldingvectors"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="opacity-60 hover:opacity-100 transition"
                  aria-label="X (Twitter)"
                >
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}
